import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import { Suspense } from "react";
import Spinner from "@/components/ui/spinner";

const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cat-Dog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} max-w-7xl my-0 mx-auto px-4 `}>
        <Header />
        <Suspense fallback={<Spinner />}> {children}</Suspense>
      </body>
    </html>
  );
}
